# Generated by Django 5.2.17 on 2026-08-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_parent_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paragraph_index',
            field=models.PositiveIntegerField(blank=True, help_text='Índice del párrafo al que pertenece (0, 1, 2...)', null=True),
        ),
    ]
