# Generated by Django 5.2.17 on 2026-08-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='followers_only',
            field=models.BooleanField(default=False, help_text='Si está activado, solo los seguidores del autor pueden leer este capítulo'),
        ),
    ]
