# Generated by Django 5.2.17 on 2026-08-19 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Cuéntale algo a la comunidad sobre ti (máx. 500 caracteres)', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil (recomendado: cuadrada, mínimo 200×200 px)', null=True, upload_to='avatars/')),
                ('website', models.URLField(blank=True, help_text='Tu blog, Twitter, Wattpad, etc.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
