# Generated by Django 5.2.17 on 2026-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilewallpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('GLOBAL', 'Tierra (Global)'), ('AR', 'Argentina'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('ES', 'España'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('DO', 'República Dominicana'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('US', 'Estados Unidos (Habla Hispana)')], default='GLOBAL', help_text='Selecciona tu país para participar en los Rankings Nacionales.', max_length=10),
        ),
    ]
