# Generated by Django 5.2.17 on 2026-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Foto de portada para tu perfil (recomendado: 1200x400 px)', null=True, upload_to='covers/'),
        ),
    ]
