# Generated by Django 6.1 on 2026-08-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('synopsis', models.TextField(max_length=2000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('genre', models.CharField(choices=[('isekai', 'Isekai'), ('fantasy_ya', 'Fantasía juvenil'), ('litrpg', 'LitRPG / Progression'), ('adventure', 'Aventura'), ('light_novel', 'Novela ligera')], max_length=20)),
                ('rating', models.CharField(choices=[('all_ages', 'Todo público'), ('teen', 'Juvenil (13+)'), ('mature_teen', 'Juvenil mayor (16+)')], default='teen', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
