# Generated by Django 5.2.17 on 2026-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('isekai', 'Isekai'), ('fantasy', 'Fantasía'), ('fantasy_ya', 'Fantasía juvenil'), ('dark_fantasy', 'Fantasía oscura'), ('litrpg', 'LitRPG / Progression'), ('scifi', 'Ciencia Ficción'), ('cyberpunk', 'Cyberpunk'), ('apocalypse', 'Post-Apocalíptico'), ('adventure', 'Aventura'), ('action', 'Acción'), ('martial_arts', 'Artes Marciales'), ('cultivation', 'Cultivo / Xianxia'), ('romance', 'Romance'), ('shoujo', 'Shōjo'), ('slice_of_life', 'Slice of Life'), ('horror', 'Horror'), ('mystery', 'Misterio'), ('light_novel', 'Novela ligera'), ('historical', 'Histórica'), ('comedy', 'Comedia')], max_length=20),
        ),
    ]
